RualesM_LigaPro/Models/Equipo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RualesM_LigaPro.Models
{
    public class Equipo
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(100)]
        [DisplayName ("Nombre del equipo: ")]
        [Required]
        public string Nombre { get; set; }
        [Range(0, 100)]
        [DisplayName("Partidos Jugados: ")]
        public int partidosJugados { get; set; }
        [Range(0, 100)]
        [DisplayName("Partidos Ganados: ")]
        public int partidosGanados { get; set; }
        [Range(0, 100)]
        [DisplayName("Partidos Perdidos: ")]
        public int partidosPerdidos { get; set; }
        [Range(0, 100)]
        [DisplayName("Partidos Empatados: ")]
        public int partidosEmpatados { get; set; }

        public int Puntos { 
            get
            {
                int puntos = (partidosGanados*3) + (partidosEmpatados*1);
                return puntos;
            } 
        }

    }
}

RualesM_LigaPro/Models/ErrorViewModel.cs
namespace RualesM_LigaPro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RualesM_LigaPro/Controllers/EquipoController.cs
using Microsoft.AspNetCore.Mvc;
using RualesM_LigaPro.Models;
using RualesM_LigaPro.Repo;

namespace RualesM_LigaPro.Controllers
{
    public class EquipoController : Controller
    {
        public IActionResult ListaEquipos()
        {
            EquipoRepo equipoRepo = new EquipoRepo();
            var equipos = equipoRepo.DevuelveListadoEquipos();
            return View(equipos);
        }

        public IActionResult Edit(int Id)
        {
            Equipo ldu = new Equipo
            {
                Id = 1,
                Nombre = "LDU",
                partidosJugados = 10,
                partidosGanados = 10,
                partidosPerdidos = 0,
                partidosEmpatados = 0
            };
            return View(ldu);
        }
    }
}

RualesM_LigaPro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RualesM_LigaPro.Models;

namespace RualesM_LigaPro.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

RualesM_LigaPro/Views/Equipo/Edit.cshtml
@model RualesM_LigaPro.Models.Equipo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Equipo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="partidosJugados" class="control-label"></label>
                <input asp-for="partidosJugados" class="form-control" />
                <span asp-validation-for="partidosJugados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="partidosGanados" class="control-label"></label>
                <input asp-for="partidosGanados" class="form-control" />
                <span asp-validation-for="partidosGanados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="partidosPerdidos" class="control-label"></label>
                <input asp-for="partidosPerdidos" class="form-control" />
                <span asp-validation-for="partidosPerdidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="partidosEmpatados" class="control-label"></label>
                <input asp-for="partidosEmpatados" class="form-control" />
                <span asp-validation-for="partidosEmpatados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puntos" class="control-label"></label>
                <input asp-for="Puntos" class="form-control" />
                <span asp-validation-for="Puntos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RualesM_LigaPro/Views/Equipo/ListaEquipos.cshtml
@model IEnumerable<RualesM_LigaPro.Models.Equipo>

@{
    ViewData["Title"] = "ListaEquipos";
}

<h1>ListaEquipos</h1>

<p>
    <a class="btn btn-info"asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.partidosJugados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.partidosGanados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.partidosPerdidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.partidosEmpatados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.partidosJugados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.partidosGanados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.partidosPerdidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.partidosEmpatados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Puntos)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id}, new { @class = "btn btn-success" })
            </td>
        </tr>
}
    </tbody>
</table>

RualesM_LigaPro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RualesM_LigaPro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RualesM_LigaPro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RualesM_LigaPro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RualesM_LigaPro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="ListaEquipos">TablaDePosiciones</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RualesM_LigaPro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>